Repository InformedSolutions/JAQU-CAZ-Payments-API, pull requests merged in 2020-03, with the labels that each got.

#174 CAZ-2054 - prod environment drone changes
  .drone.yml
Labels: do not merge

#182 Add proxy endpoint for retrieving unknown vehicle compliance
  pom.xml
  src/it/java/uk/gov/caz/psr/ExternalCallsIT.java
  src/it/java/uk/gov/caz/psr/VehicleComplianceIT.java
  src/it/resources/data/json/response/unknown-vehicle-compliance-response.json
  src/main/java/uk/gov/caz/psr/controller/PaymentsController.java
  src/main/java/uk/gov/caz/psr/controller/PaymentsControllerApiSpec.java
  src/main/java/uk/gov/caz/psr/repository/VccsRepository.java
  src/main/java/uk/gov/caz/psr/service/VehicleComplianceRetrievalService.java
  src/test/java/uk/gov/caz/psr/controller/PaymentsControllerTest.java
Labels: enhancement

#185 Permit payments to proceed in the event of one being in-flight
  src/main/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsService.java
  src/test/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsServiceTest.java
Labels: bug, enhancement

#187 Permit payments to proceed in the event of one being in-flight""
  src/main/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsService.java
  src/test/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsServiceTest.java
Labels: bug

#192 Feature/nt/alter search response
  pom.xml
  src/main/java/uk/gov/caz/psr/service/AccountService.java
  src/main/java/uk/gov/caz/psr/service/exception/AccountVehicleNotFoundException.java
  src/main/java/uk/gov/caz/psr/service/exception/ChargeableAccountVehicleNotFoundException.java
Labels: enhancement
