Repository InformedSolutions/JAQU-CAZ-Payments-API, pull requests merged in 2021-02, with the labels that each got.

#453 Promote Payments v1.7.0 to Production
  .drone.yml
  developer-resources/scripts/delete-all-payment-data.sql
Labels: IOD v1.7.0, release

#454 [CAZB-4063] Upgrade Terraform version in pipeline
  .drone.yml
  .drone2.yml
Labels: bug

#456 Promote Payments v1.7.1 to Pre-Prod
  .drone2.yml
Labels: release

#457 Promote release v1.7.2 to Pre-production
  pom.xml
  src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
Labels: release, release/v1.7.2

#458 Promote Payments v1.7.2 to Production
  .drone2.yml
  pom.xml
  src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
Labels: Payments v1.7.2, release

#466 [CAZB-4175] Fix pagination for payment-info endpoint
  src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoV2TestIT.java
  src/main/java/uk/gov/caz/psr/service/ChargeSettlementPaymentInfoService.java
  src/main/java/uk/gov/caz/psr/service/paymentinfo/CazIdSpecification.java
  src/main/java/uk/gov/caz/psr/service/paymentinfo/OmitNotPaidPaymentInfoSpecification.java
  src/main/java/uk/gov/caz/psr/service/paymentinfo/PaymentInfoSpecificationByPaymentSubmittedDate.java
  src/main/java/uk/gov/caz/psr/service/paymentinfo/PaymentInfoSpecificationPaymentId.java
  src/main/java/uk/gov/caz/psr/service/paymentinfo/PaymentInfoSpecificationTravelDateFromAndTo.java
  src/main/java/uk/gov/caz/psr/service/paymentinfo/PaymentInfoSpecificationTravelDateFromOnly.java
  src/main/java/uk/gov/caz/psr/service/paymentinfo/PaymentInfoSpecificationTravelDateToOnly.java
  src/main/java/uk/gov/caz/psr/service/paymentinfo/PaymentInfoSpecificationVrn.java
  src/main/java/uk/gov/caz/psr/service/paymentinfo/QueryUtil.java
Labels: bug
