Repository InformedSolutions/JAQU-CAZ-Payments-API, pull requests merged in 2021-06, with the labels that each got.

#543 [CAZB-4967] SpringBoot upgrade to 2.4.6
  pom.xml
Labels: do not merge

#545 [CAZB-4835] Uppercasing of CSV download content and show failed payments
  src/it/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorTestIT.java
  src/it/resources/data/csv/export/expected-payments-for-account-user.csv
  src/it/resources/data/csv/export/expected-payments-for-account.csv
  src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorStrategy.java
  src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorStrategyFactory.java
  src/main/java/uk/gov/caz/psr/service/generatecsv/LocalAuthorityCsvContentGeneratorStrategy.java
  src/test/java/uk/gov/caz/psr/service/generatecsv/BaseCsvContentGeneratorStrategyTest.java
  src/test/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorStrategyFactoryTest.java
  src/test/java/uk/gov/caz/psr/service/generatecsv/LocalAuthorityCsvContentGeneratorStrategyTest.java
Labels: enhancement

#553 [CAZB-4905] Validate user input against blacklisted characters
  .gitignore
  src/it/java/uk/gov/caz/psr/ErrorPaymentStatusUpdateTestIT.java
  src/main/java/uk/gov/caz/psr/dto/PaymentStatusRequest.java
  src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateDetails.java
  src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
Labels: documentation
