Repository InformedSolutions/JAQU-CAZ-Payments-API, pull requests merged in 2021-04, with the labels that each got.

#495 [CAZB-4428] Update libs to use new logger with request IDs
  pom.xml
Labels: enhancement

#498 [CAZB-4495] Remove endpoint for initiating CSV export
  src/main/java/uk/gov/caz/psr/controller/CsvExportController.java
  src/main/java/uk/gov/caz/psr/controller/CsvExportControllerApiSpec.java
  src/main/java/uk/gov/caz/psr/dto/PaymentHistoryCsvExportResponse.java
  src/main/resources/application.yml
  src/test/java/uk/gov/caz/psr/controller/CsvExportControllerTest.java
Labels: documentation

#499 [CAZB-4505] Add lambda handler that generates CSV file
  pom.xml
  src/it/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorTestIT.java
  src/it/java/uk/gov/caz/psr/service/generatecsv/CsvWriterTestIT.java
  src/it/java/uk/gov/caz/psr/service/generatecsv/PaymentsHistoryCsvFileSupervisorTestIT.java
  src/main/java/uk/gov/caz/psr/amazonaws/PaymentsHistoryLambdaHandler.java
  src/main/java/uk/gov/caz/psr/dto/PaymentsHistoryLambdaInput.java
  src/main/java/uk/gov/caz/psr/dto/accounts/UpdatePaymentHistoryExportRequest.java
  src/main/java/uk/gov/caz/psr/repository/AccountsRepository.java
  src/main/java/uk/gov/caz/psr/service/audit/PaymentDataCleanupService.java
  src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGenerator.java
  src/main/java/uk/gov/caz/psr/service/generatecsv/CsvFileNameGenerator.java
  src/main/java/uk/gov/caz/psr/service/generatecsv/CsvWriter.java
  src/main/java/uk/gov/caz/psr/service/generatecsv/PaymentsHistoryCsvFileSupervisor.java
  src/test/java/uk/gov/caz/psr/dto/PaymentHistoryLambdaInputTest.java
  src/test/java/uk/gov/caz/psr/service/generatecsv/PaymentsHistoryCsvFileSupervisorTest.java
Labels: documentation

#500 [CAZB-4505] Refactor `PaymentsHistoryLambdaHandler`
  src/it/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorTestIT.java
  src/main/java/uk/gov/caz/psr/amazonaws/PaymentsHistoryLambdaHandler.java
  src/main/java/uk/gov/caz/psr/service/generatecsv/PaymentHistoryExportService.java
  src/test/java/uk/gov/caz/psr/service/generatecsv/PaymentHistoryExportServiceTest.java
Labels: documentation

#501 [CAZB-4505] Add `@Component` to `PaymentHistoryExportService`
  src/main/java/uk/gov/caz/psr/service/generatecsv/PaymentHistoryExportService.java
Labels: bug
